#!/usr/bin/env node
const fs=require('node:fs');
const path=require('node:path');
const ts=require('typescript');
const args=process.argv.slice(2);
if(args.length!==2){process.stderr.write('Usage: node src/build.cjs <manifest.json> <output.html>\n');process.exit(1);}
const manifestPath=path.resolve(args[0]),dir=path.dirname(manifestPath),manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8'));
const excluded=p=>/(^|\/)(tests?|__tests__|evals?|__fixtures__|fixtures)(\/|$)|\.(test|spec|eval)\.|testHelpers/i.test(p);
const read=(revision,file)=>{const root=path.resolve(dir,manifest.sources[revision]);const target=path.resolve(root,file);if(!target.startsWith(root+path.sep))throw Error('Source path escapes snapshot: '+file);return fs.existsSync(target)?fs.readFileSync(target,'utf8'):null;};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function symbols(revision,file){const text=read(revision,file);if(text===null||!file.endsWith('.ts'))return[];const sf=ts.createSourceFile(file,text,ts.ScriptTarget.Latest,true),out=[];function visit(node){if((ts.isFunctionDeclaration(node)||ts.isMethodDeclaration(node))&&node.name&&node.body)out.push({symbol:node.name.getText(sf),className:ts.isClassDeclaration(node.parent)?node.parent.name?.getText(sf):null,line:sf.getLineAndCharacterOfPosition(node.getStart(sf)).line+1,end:sf.getLineAndCharacterOfPosition(node.end).line+1,code:node.getText(sf)});else if(ts.isVariableDeclaration(node)&&node.initializer&&(ts.isArrowFunction(node.initializer)||ts.isFunctionExpression(node.initializer)))out.push({symbol:node.name.getText(sf),line:sf.getLineAndCharacterOfPosition(node.getStart(sf)).line+1,end:sf.getLineAndCharacterOfPosition(node.end).line+1,code:node.getText(sf)});ts.forEachChild(node,visit)}visit(sf);return out;}
function extract(revision,card){const matches=symbols(revision,card.file).filter(s=>s.symbol===card.symbol&&(!card.className||s.className===card.className));if(matches.length>1)throw Error('Ambiguous symbol; supply className: '+card.symbol);return matches[0]||null;}
function visibility(source,mappings,file,revision){if(!source)return null;const represented=new Set();for(const m of mappings)if(m.source)for(let line=m.source[0];line<=m.source[1];line++)represented.add(line);const sf=ts.createSourceFile(file,read(revision,file),ts.ScriptTarget.Latest,true),ignored=new Set(),fileLines=sf.text.split('\n');function visit(node){if(ts.isExpressionStatement(node)&&ts.isCallExpression(node.expression)&&node.expression.expression.getText(sf)==='Logger.log'){const start=sf.getLineAndCharacterOfPosition(node.getStart(sf)),end=sf.getLineAndCharacterOfPosition(node.end);for(let line=start.line;line<=end.line;line++){const before=line===start.line?fileLines[line].slice(0,start.character):'';const after=line===end.line?fileLines[line].slice(end.character):'';if(!before.trim()&&!after.trim())ignored.add(line+2-source.line);}}ts.forEachChild(node,visit)}visit(sf);const eligible=source.code.split('\n').map((text,i)=>({text,line:i+1})).filter(row=>row.text.trim()&&!ignored.has(row.line));const hidden=eligible.filter(row=>!represented.has(row.line)).length;return {hidden,total:eligible.length,percent:eligible.length?Math.round(hidden/eligible.length*100):0,show:eligible.length>0&&hidden/eligible.length>.3};}
const flows=manifest.flows.map(item=>typeof item==='string'?JSON.parse(fs.readFileSync(path.resolve(dir,item),'utf8')):item).flatMap(item=>item.flows||[item]);
const cards=flows.flatMap(f=>f.cards),ids=new Set();
for(const flow of flows){if(!/^[\w-]+$/.test(flow.id)||ids.has(flow.id))throw Error('Invalid/duplicate flow id '+flow.id);ids.add(flow.id);for(const c of flow.cards){if(!/^[\w-]+$/.test(c.id)||ids.has(c.id))throw Error('Invalid/duplicate card id '+c.id);ids.add(c.id);if(excluded(c.file))throw Error('Excluded test/eval file: '+c.file);c.flowId=flow.id;c.sourceAfter=extract('head',c);c.sourceBefore=extract('base',c);if(!c.sourceAfter)throw Error('Missing head function '+c.symbol);for(const [revision,code,mappings,source] of [['after',c.after,c.mappingsAfter,c.sourceAfter],['before',c.before,c.mappingsBefore,c.sourceBefore]]){if(code==null)continue;if(!source)throw Error('Pseudocode has no original source: '+c.id+' '+revision);if(!Array.isArray(mappings))throw Error('Missing mappings for '+c.id+' '+revision);for(const m of mappings){for(const [r,max] of [[m.pseudo,code.split('\n').length],[m.source,source.code.split('\n').length]])if(!Array.isArray(r)||r.length!==2||!r.every(Number.isInteger)||r[0]<1||r[1]<r[0]||r[1]>max)throw Error('Invalid mapping '+c.id+' '+revision);}}c.status=!c.sourceBefore?'Added':c.sourceBefore.code===c.sourceAfter.code?'Context':'Modified';c.visibilityAfter=visibility(c.sourceAfter,c.mappingsAfter||[],c.file,'head');c.visibilityBefore=visibility(c.sourceBefore,c.mappingsBefore||[],c.file,'base');}}
const files=manifest.files.filter(f=>!excluded(typeof f==='string'?f:f.path)).map(input=>{const f=typeof input==='string'?{path:input}:input,before=read('base',f.path),after=read('head',f.path);if(before===null&&after===null)throw Error('Missing file '+f.path);const old=symbols('base',f.path),next=symbols('head',f.path);const changed=next.filter(s=>!old.some(o=>o.symbol===s.symbol&&o.className===s.className&&o.code===s.code)).map(s=>{const c=cards.find(c=>c.file===f.path&&c.symbol===s.symbol&&(!c.className||s.className===c.className));return {...s,code:undefined,card:c?.id||null,flow:c?.flowId||null};});for(const s of old)if(!next.some(n=>n.symbol===s.symbol&&n.className===s.className))changed.push({...s,code:undefined,card:null,flow:null,removed:true});const covered=[...new Set(cards.filter(c=>c.file===f.path).map(c=>c.flowId))];return {...f,before,after,changed,flows:covered,category:covered.length?'Slice + remaining changes':changed.length?'Not covered by a slice':'Structural/support review'};});
const types={base:{},head:{}};for(const revision of ['base','head'])for(const f of files){const text=read(revision,f.path);if(!text||!f.path.endsWith('.ts'))continue;const sf=ts.createSourceFile(f.path,text,ts.ScriptTarget.Latest,true);for(const n of sf.statements)if((ts.isTypeAliasDeclaration(n)||ts.isInterfaceDeclaration(n)||ts.isEnumDeclaration(n))&&n.name)types[revision][n.name.text]={file:f.path,code:n.getText(sf)};}
const data={title:manifest.title,url:manifest.url||'',repositoryURL:manifest.repositoryURL||'',base:manifest.baseRef,head:manifest.headRef,flows,files,types};
const css=fs.readFileSync(path.join(__dirname,'style.css'),'utf8'),runtime=fs.readFileSync(path.join(__dirname,'runtime.js'),'utf8');
const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(manifest.title)}</title><style>${css}</style></head><body><header><div class="muted">CODE SLICES / EXECUTION SLICE</div><h1>${esc(manifest.title)}</h1><p>${esc(manifest.description||'Explore selected paths through changed code.')}</p><p class="muted">${esc(manifest.baseRef)} → ${esc(manifest.headRef)} · ${files.length} implementation files</p></header><div class="layout"><aside><a href="#coverage">Changed-code index</a>${flows.map((f,i)=>`<a href="#${f.id}">${String(i+1).padStart(2,'0')} ${esc(f.title)}</a>`).join('')}<a href="#structural">Supporting changes</a><a href="#guide">Reading guide</a></aside><main><div class="toolbar"><div>Revision <button data-revision="after">After</button><button data-revision="before">Before</button><button data-revision="changes">Changes</button></div><div>View <button data-mode="pseudo">Pseudocode</button><button data-mode="split">Split</button></div><span class="muted">Hold Alt for types</span></div><section class="panel" id="coverage"><h2>Changed-code index</h2><p class="muted">Slices explain selected behavior. Changed functions outside those slices are listed explicitly. Open a file for its exact source diff.</p><div id="coverage-content"></div></section><div id="flows"></div><section class="panel" id="structural"><h2>Supporting changes</h2><div id="structural-content"></div></section><section class="panel" id="guide"><h2>Reading guide</h2><p><code>▹</code> describes the selected execution. Added APIs have no Before implementation. Changes compares complete pseudocode functions; Split also shows the source diff. Hover pairing works in Before and After.</p><p>A yellow gauge appears above 30% unmapped nonblank source lines, excluding Logger.log statements. This estimates representation, not execution coverage. Hold Alt to inspect types. The report represents authored source analysis, not an executed trace.</p></section></main></div><script type="application/json" id="review-data">${JSON.stringify(data).replace(/</g,'\\u003c')}</script><script type="module">${runtime}</script></body></html>`;
const output=path.resolve(args[1]);fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,html);process.stdout.write(JSON.stringify({output,files:files.length,flows:flows.length,cards:cards.length})+'\n');
